apiVersion: v1
kind: Pod
metadata:
    name: security-context-demo-se
spec:
    securityContext:
        seLinuxOptions:
            level: "s0:c123,c456"
    containers:
        - name: sec-ctx-3-ctr
          image: gcr.io/google-samples/node-hello:1.0
