apiVersion: v1
kind: Pod
metadata:
    name: dapi-test-pod
spec:
    containers:
        - name: test-ctr
          image: k8s.gcr.io/busybox
          command: ["/bin/sh", "-c", "env"]
          env:
              - name: SPECIAL_LEVEL_KEY
                valueFrom:
                    configMapKeyRef:
                        name: special-config
                        key: special.how
    restartPolicy: Never
