apiVersion: v1
kind: LimitRange
metadata:
    name: storagelimits
    namespace: limitrange-example
spec:
    limits:
        - type: PersistentVolumeClaim
          max:
              storage: 2Gi
          min:
              storage: 1Gi
