
apiVersion: batch/v1
kind: Job
metadata:
  name: jobexample-apple
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      name: jobexample
      labels:
        jobgroup: jobexample
    spec:
      containers:
      - name: c
        image: busybox
        command: ["sh", "-c", "echo Processing URL http://www.orangepippin.com/apples && sleep 5"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: jobexample-banana
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      name: jobexample
      labels:
        jobgroup: jobexample
    spec:
      containers:
      - name: c
        image: busybox
        command: ["sh", "-c", "echo Processing URL https://en.wikipedia.org/wiki/Banana && sleep 5"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: jobexample-raspberry
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      name: jobexample
      labels:
        jobgroup: jobexample
    spec:
      containers:
      - name: c
        image: busybox
        command: ["sh", "-c", "echo Processing URL https://www.raspberrypi.org/ && sleep 5"]
      restartPolicy: Never
---
