apiVersion: v1
kind: LimitRange
metadata:
    name: cpu-limit-range
    namespace: default-cpu-example
spec:
    limits:
        - default:
            cpu: 1
          defaultRequest:
            cpu: 0.5
          type: Container
