apiVersion: v1
kind: LimitRange
metadata:
    name: mem-min-max-demo-lr
    namespace: constraints-mem-example
spec:
    limits:
        - max:
            memory: 1Gi
          min:
            memory: 500Mi
          type: Container
