apiVersion: apps/v1
kind: Deployment
metadata:
    name: pod-quota-demo
    namespace: quota-pod-example
spec:
    selector:
        matchLabels:
            purpose: quota-demo
    replicas: 3
    template:
        metadata:
            labels:
                purpose: quota-demo
        spec:
            containers:
                - name: pod-quota-demo-ctr
                  image: nginx
