apiVersion: v1
kind: Pod
metadata:
    name: envar-demo
    labels:
        purpose: demonstrate-envars
spec:
    containers:
        - name: envar-demo-ctr
          image: gcr.io/google-samples/node-hello:1.0
          env:
              - name: DEMO_GREETING
                value: "Hello from the environment"
              - name: DEMO_FAREWELL
                value: "Such a sweet sorrow"
          command: ["echo"]
          args: ["$(DEMO_GREETING) $(DEMO_FAREWELL)"]
