apiVersion: v1
kind: Pod
metadata:
    name: envfrom-secret
spec:
    containers:
        - name: envars-test-ctr
          image: nginx
          envFrom:
              - secretRef:
                  name: test-secret
