apiVersion: v1
kind: Pod
metadata:
    name: envars-multiple-secrets
spec:
    containers:
        - name: envars-test-ctr
          image: nginx
          env:
              - name: BACKEND_USERNAME
                valueFrom:
                    secretKeyRef:
                        name: backend-user
                        key: backend-username
              - name: DB_USERNAME
                valueFrom:
                    secretKeyRef:
                        name: db-user
                        key: db-username
