apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
    labels:
        dapp: nginx
spec:
    selector:
        matchLabels:
            app: nginx
    minReadySeconds: 5
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx-ctr
                  image: nginx:1.7.9
                  ports:
                      - containerPort: 80
