# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# pods "command-demo" was not valid:
# * : Invalid value: "The edited file failed validation": [yaml: invalid leading UTF-8 octet, invalid character 'a' looking for beginning of value]
#
apiVersion: v1
kind: Pod
metadata:
  labels:
    purpose: demonstrate-command
  name: command-demo
  namespace: default
spec:
  containers:
  - args: ["$(MESSAGE)"]
    command:
    - echo
    env:
        - name: MESSAGE
          value: "Hello, DÁìúì•ÔºÅ"
    image: debian
    name: command-demo-ctr
  restartPolicy: OnFailure
